<a href="https://colab.research.google.com/github/Auzek2002/Iris_Classification_Using_ANN/blob/main/Iris_Classification_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libs:

In [209]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import cv2 as cv
from tensorflow.keras import datasets,layers,Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# **Loading the DataSet**

In [210]:
df = datasets.load_iris()

In [211]:
type(df)

sklearn.utils._bunch.Bunch

In [212]:
df.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [213]:
df.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [214]:
class_names = df.target_names

In [215]:
class_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [216]:
x = df.data

In [217]:
y=df.target

In [218]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [219]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


# **Split the Data into Training and Testing Samples**

In [220]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.05,random_state=42)

# **Feature Scaling**

Before scaling:

In [221]:
print(f"Max value of train features is: {np.max(x_train)} and Min value of train features is: {np.min(x_train)}")
print(f"Max value of test features is: {np.max(x_test)} and Min value of test features is: {np.min(x_test)}")

Max value of train features is: 7.9 and Min value of train features is: 0.1
Max value of test features is: 7.7 and Min value of test features is: 0.3


In [222]:
scaler = StandardScaler()

In [223]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

After scaling:

In [224]:
print(f"Max value of train features is: {np.max(x_train)} and Min value of train features is: {np.min(x_train)}")
print(f"Max value of test features is: {np.max(x_test)} and Min value of test features is: {np.min(x_test)}")

Max value of train features is: 3.0627286721571356 and Min value of train features is: -2.4164205744105907
Max value of test features is: 2.2848354463998333 and Min value of test features is: -1.2707685793652905


# **Building the Neural Network**

In [225]:
!pip install keras-tuner

In [226]:
def build_model(hp):
  model = Sequential([
    layers.Dense(
        units=hp.Int('dense_1_units', min_value=32, max_value=512, step=16),
        activation=hp.Choice('dense_1_activation',values= ['relu','selu','tanh','elu','sigmoid']),
        input_dim=4
    ),
    layers.Dense(3, activation='softmax')
  ])

  model.compile(optimizer=tf.keras.optimizers.Adam(hp.Choice('learning_rate', values=[0.0001,0.0003,0.001,0.003,0.01])),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

  return model

In [227]:
from kerastuner import RandomSearch
from kerastuner.engine.hyperparameters import HyperParameters

# **Search for the best Hyperparameters**

In [228]:
tuner_search = RandomSearch(build_model,objective='val_accuracy',max_trials=15,directory='output',project_name='Iris_Classification_System_1.0')

Reloading Tuner from output/Iris_Classification_System_1.0/tuner0.json


In [229]:
tuner_search.search(x_train,y_train,epochs=3,validation_split=0.1)

In [230]:
model = tuner_search.get_best_models(num_models=1)[0]

In [231]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 272)               1360      
                                                                 
 dense_1 (Dense)             (None, 3)                 819       
                                                                 
Total params: 2179 (8.51 KB)
Trainable params: 2179 (8.51 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# **Fitting the Model**

In [232]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=150,initial_epoch=3)

Epoch 4/150
5/5 [==============================] - 1s 55ms/step - loss: 0.5010 - accuracy: 0.8380 - val_loss: 0.4892 - val_accuracy: 0.6250
Epoch 5/150
5/5 [==============================] - 0s 9ms/step - loss: 0.3354 - accuracy: 0.8592 - val_loss: 0.3496 - val_accuracy: 0.7500
Epoch 6/150
5/5 [==============================] - 0s 8ms/step - loss: 0.2696 - accuracy: 0.8732 - val_loss: 0.1929 - val_accuracy: 1.0000
Epoch 7/150
5/5 [==============================] - 0s 8ms/step - loss: 0.2048 - accuracy: 0.9225 - val_loss: 0.2207 - val_accuracy: 0.8750
Epoch 8/150
5/5 [==============================] - 0s 10ms/step - loss: 0.1861 - accuracy: 0.8873 - val_loss: 0.1727 - val_accuracy: 1.0000
Epoch 9/150
5/5 [==============================] - 0s 9ms/step - loss: 0.1301 - accuracy: 0.9507 - val_loss: 0.0651 - val_accuracy: 1.0000
Epoch 10/150
5/5 [==============================] - 0s 9ms/step - loss: 0.1306 - accuracy: 0.9507 - val_loss: 0.0643 - val_accuracy: 1.0000
Epoch 11/150
5/5 [======

# **Evaluating the Model**

In [233]:
score = model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 87ms/step - loss: 4.6330e-04 - accuracy: 1.0000


In [234]:
print(f"Accuracy of the model is: {score[1]*100:0.2f}%")

Accuracy of the model is: 100.00%
